config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reuniaos
  #get 'home/index'
  root 'home#index'
 
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reuniao.rb
class Reuniao < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :reuniaos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reuniaos_controller.rb
class ReuniaosController < ApplicationController
  before_action :set_reuniao, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /reuniaos or /reuniaos.json
  def index
    @reuniaos = Reuniao.all
  end

  # GET /reuniaos/1 or /reuniaos/1.json
  def show
  end

  # GET /reuniaos/new
  def new
    @reuniao = Reuniao.new
  end

  # GET /reuniaos/1/edit
  def edit
  end

  # POST /reuniaos or /reuniaos.json
  def create
    @reuniao = Reuniao.new(reuniao_params)

    respond_to do |format|
      if @reuniao.save
        format.html { redirect_to @reuniao, notice: "Reuniao foi marcada com sucesso." }
        format.json { render :show, status: :created, location: @reuniao }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reuniao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reuniaos/1 or /reuniaos/1.json
  def update
    respond_to do |format|
      if @reuniao.update(reuniao_params)
        format.html { redirect_to @reuniao, notice: "Reuniao atualizada com sucesso." }
        format.json { render :show, status: :ok, location: @reuniao }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reuniao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reuniaos/1 or /reuniaos/1.json
  def destroy
    @reuniao.destroy
    respond_to do |format|
      format.html { redirect_to reuniaos_url, notice: "Reuniao foi cancelada com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reuniao
      @reuniao = Reuniao.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reuniao_params
      params.require(:reuniao).permit(:nome_completo, :data, :descricao, :user_id)
    end

    def modal
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reuniaos_helper.rb
module ReuniaosHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%= link_to	'App Agenda', root_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Agenda', reuniaos_path, class:"nav-link" %>
        </li>
        
      

        <% if user_signed_in? %>

        <li class="nav-item">
          <%= link_to 'Nova Reserva', new_reuniao_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Editar Conta', edit_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Sair',  destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>

        <% else %>
        <li class="nav-item">
          <%= link_to 'Registrar', new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Entrar', new_user_session_path, class:"nav-link" %>
        </li>

        <% end %>
        

      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>BEM VINDO AO SISTEMA DE AGENDAMENTO DE REUNIAO</h1>


<a href="#" onclick="paintIt(event, '#990000')">Paint it red</a>
<a href="#" onclick="paintIt(event, '#009900', '#FFFFFF')">Paint it green</a>
<a href="#" onclick="paintIt(event, '#000099', '#FFFFFF')">Paint it blue</a>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <% notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Reunião</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
   

    <%= render 'home/header'%>

    <div class="container">
      <br>
      <% if notice %>
      <%= render "layouts/alerts" %>
      <% end %>

      <br>
      <%= yield %>  
    </div>
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/reuniaos/_form.html.erb
<%= form_with(model: reuniao) do |form| %>
  <% if reuniao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reuniao.errors.count, "error") %> prohibited this reuniao from being saved:</h2>

      <ul>
        <% reuniao.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :nome_completo %>
    <%= form.text_field :nome_completo, class:"form-control" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :data %>
    <%= form.datetime_select :data, class:"form-control" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :descricao %>
    <%= form.text_field :descricao, class:"form-control" %>
  </div>
  <br>
  <div class="field form-group">
    
  <%= form.number_field :user_id, id: :reuniao_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>

<br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reuniaos/edit.html.erb
<h1>Editing Reuniao</h1>

<%= render 'form', reuniao: @reuniao %>

<%= link_to 'Show', @reuniao %> |
<%= link_to 'Back', reuniaos_path %>

app/views/reuniaos/index.html.erb
<h1>Lista de Agendamentos</h1>
<table class="table table-dark table-hover table-striped table-bordered">
  <thead class="thead-dark">
    <tr>
      <th>Nome completo</th>
      <th>Data</th>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reuniaos.each do |reuniao| %>
      <tr>
        <td><%= reuniao.nome_completo %></td>
        <td><%= reuniao.data %></td>
        <td><%= reuniao.descricao %></td>
        <td><%= link_to 'Detalhes', reuniao %></td>
        
        <% if reuniao.user == current_user %>
        <td><%= link_to 'Editar', edit_reuniao_path(reuniao) %></td>
        <td><%= link_to 'Excluir', reuniao, method: :delete, data: { confirm: 'Voce tem certeza?' } %></td>

        <%else%>
        <td></td>
        <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>


</table>







                                    <!-- Modal -->
                                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                      <div class="modal-dialog">
                                        <div class="modal-content">
                                          <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Reservar Sala</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                          </div>
                                          <div class="modal-body">
                                            
                                          </div>
                                          <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                            <button type="button" class="btn btn-primary">Save changes</button>
                                          </div>
                                        </div>
                                      </div>
                                    </div>


<div class="container">
                <div class="timetable-img text-center">
                    <img src="img/content/timetable.png" alt="">
                </div>
                <div class="table-responsive">
                    <table class="table table-bordered text-center table table-striped">
                        <thead>
                            <tr class="bg-light-gray">
                                <th class="text-uppercase">Horários
                                </th>
                                <th class="text-uppercase">Segunda-Feira</th>
                                <th class="text-uppercase">Terça-Feira</th>
                                <th class="text-uppercase">Quarta-Feira</th>
                                <th class="text-uppercase">Quinta-Feira</th>
                                <th class="text-uppercase">Sexta-Feira</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                            
                           <tr>
                                <td class="align-middle">07:00</td>
                                <td>
                                    <!-- Button trigger modal -->
                                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                      Disponivel
                                    </button>

                                    
                                </td>
                                <td>
                                   <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                      Disponivel
                                    </button>
                              </td>
                                <td>
                                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                      Disponivel
                                    </button>
                                </td>

                                <td>
                                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                      Disponivel
                                    </button>
                                </td>
                                    
                                </td>
                               
                                <td>
                                  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                      Disponivel
                                    </button>

                                </td>

                            </tr>
                            <tr>
                                <td class="align-middle">09:00</td>
                                <td>
                                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                      Disponivel
                                    </button>
                                </td>
                                <td>
                                   <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                      Disponivel
                                    </button>
                                </td>

                                <td>
                                   <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                      Disponivel
                                    </button>
                                </td>
                                <td>
                                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                      Disponivel
                                    </button>
                                </td>
                                <td>
                                   <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                      Disponivel
                                    </button>
                                </td>

                            </tr>

                            <tr>
                                <td class="align-middle">10:00</td>
                                <td>
                           


                                </td>
                                <td>
                                   
                                </td>
                                <td>
                                  
                                <td>
                                   
                                </td>
                                <td>

                                </td>
                            </tr>

                            <tr>
                                <td class="align-middle">11:00</td>
                                <td>
                                  
                                </td>
                                <td>
                                   
                                </td>
                                <td>
                                   
                                </td>
                                <td>
                                  
                                </td>
                                <td>
                                  
                                </td>

                            </tr>

                            <tr>
                                <td class="align-middle">12:00</td>
                                <td class="bg-light-gray">

                                </td>
                                <td>
                                   
                                </td>
                                <td>
                                   
                                </td>
                                <td>
                                   
                                </td>
                                <td class="bg-light-gray">

                                </td>

                            </tr>

                                
                        </tbody>
                    </table>
                </div>
            </div>

app/views/reuniaos/new.html.erb
<h1>Agendar Reserva</h1>

<%= render 'form', reuniao: @reuniao %>

<%= link_to 'Back', reuniaos_path %>

app/views/reuniaos/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @reuniao.nome_completo %></h1>
  <p class="lead"><%= @reuniao.data %></p>
  <hr class="my-4">
  <p><%= @reuniao.descricao %></p>

  <%= link_to 'Editar', edit_reuniao_path(@reuniao) %> 
<%= link_to 'Voltar', reuniaos_path %>
</div>